### ISSUE TITLE
Maximum number of redirects exceeded

### ISSUE THREAD

**Issue by aksheetha** [pratik-dani/LinkedIn-Scraper#4]
Hello Pratik, I was able to scrape some profile last week but now I am not able to i am getting this error "Maximum number of redirects exceeded" Please let me know if something i am doing wrong

**Comment by pratik-dani** [comment]
Hey,
This generally implies that your session cookies have expired. I will handle this exception, to give an appropriate message.

**Comment by aksheetha** [comment]
Thanks Pratik, I have a few questions:

1. Do I need to change cookies for every scraping?

2. Is there a limit to the number of profiles I can scrape?
