### ISSUE TITLE
Can this be converted into an API?

### ISSUE THREAD

**Issue by Kolaposki** [pratik-dani/LinkedIn-Scraper#6]
Would be great if this can be converted to an API that returns just json provided the url of the person.

**Comment by pratik-dani** [comment]
The idea of this project is create an open-source which is easily usable and free to extract data from your LinkedIn account, without paying for tools like phantombuster, etc, plus there are a lot of open-source available which you can to extract data programatically one such repo is [this one](https://github.com/tomquirk/linkedin-api). Closing this for now.
